/**
 * User Mapper — 领域实体 ↔ Prisma 持久化模型转换
 *
 * Clean Architecture 的关键实践：领域实体和持久化模型分离。
 * - 领域实体（User）：纯 TS 类，封装业务规则，不含 ORM 装饰器
 * - Prisma 模型（User as generated by Prisma）：数据库映射，含字段类型
 *
 * Mapper 负责两者之间的双向转换，确保领域层不感知持久化细节。
 */

import { User } from "../../../domain/user/user.entity.js";

/**
 * Prisma 生成的 User 类型（对应 schema.prisma 中的 model User）
 */
interface UserPrismaModel {
  id: string;
  email: string;
  name: string;
  createdAt: Date;
  updatedAt: Date;
}

export class UserMapper {
  /**
   * Prisma 模型 → 领域实体
   * 使用 reconstitute 工厂方法，保留原始 ID 和时间戳
   */
  static toDomain(prismaModel: UserPrismaModel): User {
    return User.reconstitute({
      id: prismaModel.id,
      email: prismaModel.email,
      name: prismaModel.name,
      createdAt: prismaModel.createdAt,
      updatedAt: prismaModel.updatedAt,
    });
  }

  /**
   * 领域实体 → Prisma 模型（用于 create/update 操作）
   */
  static toPersistence(user: User): UserPrismaModel {
    return {
      id: user.id,
      email: user.email.value,
      name: user.name,
      createdAt: user.createdAt,
      updatedAt: user.updatedAt,
    };
  }
}